# Example configuration file of blocky DNS for the lists updater (https://github.com/shizunge/blocky-lists-updater)
blocking:
  # definition of blacklist groups. Can be external link (http/https) or local file
  # The static-web-server allows multiple blocky instance to access the same set of files.
  denylists:
    # Ask blocky to download lists from the static-web-server of the lists-updater.
    # The watch folder contains user defined lists.
    # The downloaded folder contains aggregate lists for given sources files.
    my-lists:
      - http://lists-updater:8080/watch/blocked-list.txt
    default-lists:
      - http://lists-updater:8080/downloaded/default-lists.txt
    group-one:
      - http://lists-updater:8080/downloaded/list-one.txt
    group-two:
      - http://lists-updater:8080/downloaded/list-two.txt
  allowlists:
    my-lists:
      - http://lists-donwloader:8080/watch/allowed-list.txt
  clientGroupsBlock:
    # default will be used, if no special definition for a client name exists
    default:
      - my-lists
      - default-lists
      - group-one
      - group-two
  blockType: zeroIp
  blockTTL: 1h
  loading:
    # Disable build-in refreshing, only listens to lists updater refreshing requests.
    refreshPeriod: 0
    downloads:
      timeout: 5m
      attempts: 60
      cooldown: 5s
    concurrency: 4
    strategy: failOnError
    # Forgive the errors in the aggregate lists. The aggregate one also contains all errors from all of lists.
    maxErrorsPerSource: -1

upstreams:
  groups:
    default:
      - tcp-tls:one.one.one.one:853
  strategy: parallel_best
  timeout: 5s
  init:
    strategy: failOnError

connectIPVersion: dual

caching:
  minTime: 1m
  maxTime: 0m
  maxItemsCount: 0
  prefetching: true
  prefetchExpires: 2h
  prefetchThreshold: 5
  prefetchMaxItemsCount: 0
  cacheTimeNegative: 30s

queryLog:
  # You may also like https://github.com/shizunge/blocky-postgresql
  type: postgresql
  target: postgres://blocky:blocky@blocky_db.blocky_network:5432/blocky
  logRetentionDays: 45
  creationAttempts: 60
  creationCooldown: 5s

bootstrapDns:
  - tcp+udp:127.0.0.11

hostsFile:
  sources:
    - /etc/hosts
  hostsTTL: 1h
  filterLoopback: true
  loading:
    refreshPeriod: 1h

ports:
  dns: 53
  tls: 853
  https: 443
  http: 4000

